package com.miniproject.qpgenerator.paper.controller;

import com.miniproject.qpgenerator.paper.dto.PaperDetailResponse;
import com.miniproject.qpgenerator.paper.dto.PaperQuestionDetailResponse;
import com.miniproject.qpgenerator.paper.service.PaperHistoryService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping("/api/papers/history")
@RequiredArgsConstructor
public class PaperHistoryController {

    private final PaperHistoryService paperHistoryService;

    /**
     * Get all papers by subject code
     */
    @GetMapping("/subject/{subjectCode}")
    public ResponseEntity<List<PaperDetailResponse>> getPapersBySubject(
            @PathVariable String subjectCode) {
        List<PaperDetailResponse> papers = paperHistoryService.getPapersBySubject(subjectCode);
        return ResponseEntity.ok(papers);
    }

    /**
     * Get papers by subject and exam type
     */
    @GetMapping("/subject/{subjectCode}/exam-type/{examType}")
    public ResponseEntity<List<PaperDetailResponse>> getPapersBySubjectAndExamType(
            @PathVariable String subjectCode,
            @PathVariable String examType) {
        List<PaperDetailResponse> papers = paperHistoryService.getPapersBySubjectAndExamType(subjectCode, examType);
        return ResponseEntity.ok(papers);
    }

    /**
     * Get all papers generated by a faculty
     */
    @GetMapping("/faculty/{facultyId}")
    public ResponseEntity<List<PaperDetailResponse>> getPapersByFaculty(
            @PathVariable Long facultyId) {
        List<PaperDetailResponse> papers = paperHistoryService.getPapersByFaculty(facultyId);
        return ResponseEntity.ok(papers);
    }

    /**
     * Get papers by faculty and subject
     */
    @GetMapping("/faculty/{facultyId}/subject/{subjectCode}")
    public ResponseEntity<List<PaperDetailResponse>> getPapersByFacultyAndSubject(
            @PathVariable Long facultyId,
            @PathVariable String subjectCode) {
        List<PaperDetailResponse> papers = paperHistoryService.getPapersByFacultyAndSubject(facultyId, subjectCode);
        return ResponseEntity.ok(papers);
    }

    /**
     * Get papers by faculty, subject, and exam type
     */
    @GetMapping("/faculty/{facultyId}/subject/{subjectCode}/exam-type/{examType}")
    public ResponseEntity<List<PaperDetailResponse>> getPapersByFacultySubjectAndExamType(
            @PathVariable Long facultyId,
            @PathVariable String subjectCode,
            @PathVariable String examType) {
        List<PaperDetailResponse> papers = paperHistoryService.getPapersByFacultySubjectAndExamType(facultyId, subjectCode, examType);
        return ResponseEntity.ok(papers);
    }

    /**
     * Get single paper detail with all questions
     */
    @GetMapping("/{paperId}")
    public ResponseEntity<Map<String, Object>> getPaperById(
            @PathVariable Long paperId) {
        Map<String, Object> paper = paperHistoryService.getPaperById(paperId);
        return ResponseEntity.ok(paper);
    }

    /**
     * Get questions for a specific set
     */
    @GetMapping("/{paperId}/set/{setNo}")
    public ResponseEntity<List<PaperQuestionDetailResponse>> getPaperSetQuestions(
            @PathVariable Long paperId,
            @PathVariable Integer setNo,
            @RequestParam(required = false) String part) {
        List<PaperQuestionDetailResponse> questions = paperHistoryService.getPaperSetQuestions(paperId, setNo, part);
        return ResponseEntity.ok(questions);
    }

    /**
     * Get Part A questions for a set
     */
    @GetMapping("/{paperId}/set/{setNo}/part-a")
    public ResponseEntity<List<PaperQuestionDetailResponse>> getPaperSetPartA(
            @PathVariable Long paperId,
            @PathVariable Integer setNo) {
        List<PaperQuestionDetailResponse> questions = paperHistoryService.getPaperSetPartA(paperId, setNo);
        return ResponseEntity.ok(questions);
    }

    /**
     * Get Part B questions for a set
     */
    @GetMapping("/{paperId}/set/{setNo}/part-b")
    public ResponseEntity<List<PaperQuestionDetailResponse>> getPaperSetPartB(
            @PathVariable Long paperId,
            @PathVariable Integer setNo) {
        List<PaperQuestionDetailResponse> questions = paperHistoryService.getPaperSetPartB(paperId, setNo);
        return ResponseEntity.ok(questions);
    }

    /**
     * Delete a paper
     */
    @DeleteMapping("/{paperId}")
    @PreAuthorize("hasRole('ADMIN') or hasRole('FACULTY')")
    public ResponseEntity<String> deletePaper(
            @PathVariable Long paperId) {
        paperHistoryService.deletePaper(paperId);
        return ResponseEntity.ok("Paper deleted successfully");
    }
}
